# https://docs.getdbt.com/reference/warehouse-profiles/postgres-profile

default:
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'postgres') }}"
      port: "{{ env_var('POSTGRES_PORT', 5432) | int }}"
      user: "{{ env_var('POSTGRES_USER', 'dbt_user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'dbt_password') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'dbt_dev') }}"
      schema: raw
      threads: 4
      keepalives_idle: 0
  target: dev